"""Pydantic schemas for the architecture explanation API responses."""

from pydantic import BaseModel, Field

from app.schemas.framework import ProjectInfo


class ExplanationResponse(BaseModel):
    """Complete response returned by POST /explain/{upload_id}."""

    project: ProjectInfo = Field(description="Project metadata")
    overview: str = Field(description="Full architecture generated by the LLM")
    architecture_style: str = Field(default="", description="Detected architectural style")
    technology_stack: list[str] = Field(default_factory=list, description="Technology stack components")
    major_modules: list[str] = Field(default_factory=list, description="Major modules identified")
    data_flow: str = Field(default="", description="Data flow description")
    design_patterns: list[str] = Field(default_factory=list, description="Key design patterns identified")
    strengths: list[str] = Field(default_factory=list, description="Architectural strengths")
    improvements: list[str] = Field(default_factory=list, description="Potential improvements")
    scalability: str = Field(default="", description="Scalability notes")
    maintainability: str = Field(default="", description="Maintainability notes")
